export const MENU = [
  {
    id: 1,
    title: "Fluffy Pancakes",
    category: "Breakfast",
    price: 12.49,
    img: "./images/task8-images/pancake.jpg",
    desc: "Delicious buttermilk pancakes topped with fresh berries and maple syrup.",
  },
  {
    id: 2,
    title: "Classic Burger",
    category: "Lunch",
    price: 9.99,
    img: "/images/task8-images/burger.jpg",
    desc: "Juicy beef patty, melted cheddar, lettuce, and secret sauce on a sesame seed bun.",
  },
  {
    id: 3,
    title: "Choco Banana Shake",
    category: "Shakes",
    price: 5.49,
    img: "/images/task8-images/fruits.jpg",
    desc: "Creamy chocolate shake blended with ripe bananas and a hint of vanilla.",
  },
  {
    id: 4,
    title: "Veggie Omelette",
    category: "Breakfast",
    price: 14.99,
    img: "./images/task8-images/eggs.jpg",
    desc: "Three-egg omelette filled with spinach, bell peppers, and feta cheese.",
  },
  {
    id: 5,
    title: "Spicy Tofu Bowl",
    category: "Lunch",
    price: 11.49,
    img: "./images/task8-images/fish.jpg",
    desc: "Crispy tofu, brown rice, avocado, and a zesty sriracha-lime dressing.",
  },
  {
    id: 6,
    title: "Berry Blast Smoothie",
    category: "Shakes",
    price: 7.99,
    img: "./images/task8-images/bread.jpg",
    desc: "Mixed berry smoothie with Greek yogurt, honey, and a sprinkle of granola.",
  }
];
